version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"   
    environment:
      - DATABASE_URL=postgresql://postgres:vipaVWeMZJTlrcrecFjBgUDzUVKpqaSG@shortline.proxy.rlwy.net:16775/railway
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - PUBLIC_API_URL=http://localhost:3000
    ports:
      - "8082:80"    
    depends_on:
      - backend
    restart: unless-stopped
