name: Construir aplicación fullstack
run-name: Construir backend y frontend

on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      #  Construir backend
      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install

      - name: Ejecutar lint en el backend
        working-directory: ./backend
        run: npm run lint

      - name: Compilar backend
        working-directory: ./backend
        run: npm run build

      #  Construir frontend
      - name: Instalar dependencias del frontend
        working-directory: ./frontend
        run: npm install

      - name: Ejecutar lint en el frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Compilar frontend
        working-directory: ./frontend
        run: npm run build
