name: Node build
run-name: Build backend y frontend
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # Backend
      - name: Instalar dependencias backend
        working-directory: ./backend
        run: |
          npm install

      - name: Compilar backend
        working-directory: ./backend
        run: |
          npm run build

      # Frontend
      - name: Instalar dependencias frontend
        working-directory: ./frontend
        run: |
          npm install

      - name: Compilar frontend
        working-directory: ./frontend
        run: |
          npm run build
