name: Node Test
run-name: Test backend y frontend

on: [push]

jobs:
  test:
    runs-on: [self-hosted]

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # Backend
      - name: Instalar dependencias backend
        working-directory: ./backend
        run: npm install

      - name: Generar cliente de Prisma
        working-directory: ./backend
        run: npx prisma generate
        env:
          DATABASE_URL: "postgresql://postgres:vipaVWeMZJTlrcrecFjBgUDzUVKpqaSG@shortline.proxy.rlwy.net:16775/railway"

      - name: Ejecutar tests en backend
        working-directory: ./backend
        run: npm test
        env:
          DATABASE_URL: "postgresql://postgres:vipaVWeMZJTlrcrecFjBgUDzUVKpqaSG@shortline.proxy.rlwy.net:16775/railway"

      # Frontend
      - name: Instalar dependencias frontend
        working-directory: ./frontend
        run: npm install

      - name: Ejecutar tests en frontend
        working-directory: ./frontend
        run: npm test
